---
title: "Excercise 2 - Solutions"
author: "Martin Modrák"
date: "2021/08/24 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: ./libs
    css: ["hygge", "middlebury-fonts", "ninjutsu"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(cmdstanr)
library(SBC)

if(packageVersion("SBC") < package_version("0.1.0.0")) {
  stop(paste0("This tutorial has been updated for SBC 0.1, please update your SBC installation"))
}


knitr::opts_chunk$set(echo=FALSE, cache = TRUE, fig.width = 5, fig.height=4)
```


```{r computeSBC, results="hide", include = FALSE}
model_gamma <- cmdstan_model("gamma.stan")

backend_gamma <- SBC_backend_cmdstan_sample(
    model_gamma, # <- model is first argument
    # additional args passed to to model$sample() directly 
    iter_warmup = 500, iter_sampling = 1000, chains = 2)

# N - the number of observed datapoints
single_sim_gamma <- function(N) {
  shape <- rlnorm(n = 1, meanlog =  0, sdlog = 1)
  scale <- rlnorm(n = 1, meanlog = 0, sdlog = 1.5)
  y <- rgamma(N, shape = shape, scale = scale)
  
  list(
    # True, unobserved
    variables = list(
      shape = shape,
      scale = scale),
    # Observed data, passed directly to Stan
    generated = list(
      N = N,
      y = y)
  )
}


generator_gamma <- SBC_generator_function(
  # Passing single_sim_gamma as a parameter, 
  # not calling it
  single_sim_gamma, 
  # Additional arguments are passed to the function
  # Here we only use N
  N = 40)
  
datasets_gamma <- generate_datasets(
  generator_gamma, 
  n_sims = 10)

results_gamma <- compute_SBC(
                   datasets_gamma, backend_gamma)
```



```{r, fig.width = 4.5, fig.height=4}
plot_rank_hist(results_gamma, bins = 10)
plot_ecdf(results_gamma)
plot_ecdf_diff(results_gamma)
```

---

## Correcting the parametrization

Where we had

```stan
  y ~ gamma(shape, scale);
```

we need

```stan
  y ~ gamma(shape, 1/scale);
```

--

(or we could change the simulator to use `rate` instead)

---
